language:  python
python:
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:  
  - "sudo apt-get update"
install:  
  - "pip install -r requirements.txt"
script:
  - "ls -la"
  - "pwd"
  - "nose2 -v --with-coverage"
notifications:
  email: 
    - livysdad27@gmail.com
after_script:
  - coveralls
