language:  python
python:
  - "3.5"
before_install:  
  - "sudo apt-get update"
install:  
  - "pip install -r requirements.txt"
script:
  - "ls -la"
  - "pwd"
  - "nose2 -v --with-coverage --coverage-config tests/coveragerc"
notifications:
  email: 
    - livysdad27@gmail.com
after_script:
  - coveralls
